### ISSUE TITLE
Dynamic Lights support

### ISSUE THREAD

**Issue by Shinoow** [Shinoow/Hungering-Darkness#2]
I already have all of the necessary code for this in Grue. Simply put, the client alerts the server on world load whether or not they have Dynamic Lights installed, then the server handles all of the logic determining whether or not the player is currently holding a light source (through the use of a configurable list of things considered light sources). The client has no control apart from saying "hey, I have this mod installed".
Might as well also add a config option for toggling this, in the event that the feature isn't needed or unwanted in some scenario.

**Comment by naqaden** [comment]
Please consider supporting handheld light sources simply from this mod's own items/blocks config. I think expanding that list to include light levels would be an easy way to allow any dynamic lights mod to "work" with HD.

For example, minecraft:glowstone,15 would treat a player holding glowstone as if they were standing in level 15 light without involving any mod. A player with Optifine's dynamic lights could synchronize light source configs between mods to enjoy this feature without being restricted to AtomicStryker's Dynamic Lights.
