### ISSUE TITLE
Light levels on Farmland

### ISSUE THREAD

**Issue by jlaw21** [Shinoow/Hungering-Darkness#6]
#### Description:

Standing on farmland does damage regardless of surrounding light levels.

#### Crash report:

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2821
- Hungering Darkness: 1.12.2-1.2.0

**Comment by Shinoow** [comment]
Should be solved by the changes introduced in 1.3.0!
